"""Create SuspiciousIP Model

Revision ID: 3775e91ddd21
Revises: 
Create Date: 2024-01-23 22:39:12.270092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3775e91ddd21'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suspicious_ip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('report_count', sa.Integer(), nullable=True),
    sa.Column('last_report_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suspicious_ip_id'), 'suspicious_ip', ['id'], unique=False)
    op.create_index(op.f('ix_suspicious_ip_ip_address'), 'suspicious_ip', ['ip_address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suspicious_ip_ip_address'), table_name='suspicious_ip')
    op.drop_index(op.f('ix_suspicious_ip_id'), table_name='suspicious_ip')
    op.drop_table('suspicious_ip')
    # ### end Alembic commands ###
